import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ViewTransitions } from "next-view-transitions";
const geistSans = Geist({ 
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="fr">    
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
           {children}
           {/* Élément revealer pour les animations de transition */}
           <div className="revealer"></div>
      </body>
    </html>
    </ViewTransitions>
  );
}
